app/models.py
from . import db

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    role = db.Column(db.String(20), default='user', nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    hashed_password = db.Column(db.String(220),nullable=False)
    

    def __repr__(self):
        return f'<User {self.name}>'

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from dotenv import load_dotenv
import os

load_dotenv()

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = os.getenv('SECRET_KEY', 'df77ecd4d372091361511579f04aa697c6d73b5d5169f288')
    app.config['SQLALCHEMY_DATABASE_URI'] = os.getenv('DATABASE_URI')
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    
    db.init_app(app)
    migrate.init_app(app, db)

    from .routes import main
    app.register_blueprint(main)
    
    # uncomment kode dibawah ini untuk menjalankan data seeder akun admin,
    # karena pada kasus ini untuk crud dapat dilakukan semua user login maka tidak perlu digunakan
    
    # with app.app_context():
    #     from .seeder import seed_data
    #     seed_data()
    

    return app

app/routes.py
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, session, flash
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from .models import User

main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def home():
    if 'loggedin' in session:
        page = request.args.get('page', 1, type=int)
        per_page = 5
        users = User.query.paginate(page=page, per_page=per_page)
        return render_template('index.html', username=session['username'], role=session['role'], users=users)
    else:
        flash('Please log in to access this page.', 'warning')
        return redirect(url_for('main.login'))

@main.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        
        if password == confirm_password:
            existing_email = User.query.filter_by(email=email).first()
            existing_username = User.query.filter_by(username=username).first()
            
            if existing_email:
                flash('Email already exists!', 'danger')
                return render_template('register.html')
            
            if existing_username:
                flash('Username already exists!', 'danger')
                return render_template('register.html')
            
            hashed_password = generate_password_hash(password)
            new_user = User(username=username, email=email, hashed_password=hashed_password)
            db.session.add(new_user)
            db.session.commit()

            flash('You have successfully registered! Please log in.', 'success')
            return redirect(url_for('main.login'))
        else:
            flash('Passwords do not match!', 'danger')
            return render_template('register.html')
        
    return render_template('register.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.hashed_password, password):
            session['loggedin'] = True
            session['id'] = user.id
            session['username'] = user.username
            session['role'] = user.role
            flash('Login successful!', 'success')
            return redirect(url_for('main.home'))
        else:
            flash('Invalid email or password!', 'danger')

    return render_template('login.html')


@main.route('/logout', methods=['POST'])
def logout():
    session.clear()
    flash('You have been logged out.', 'success')
    return redirect(url_for('main.login'))

@main.route('/create', methods=['GET', 'POST'])
def create():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        
        if password == confirm_password:
            existing_email = User.query.filter_by(email=email).first()
            existing_username = User.query.filter_by(username=username).first()
            
            if existing_email:
                flash('Email already exists!', 'danger')
                return render_template('create.html')
            
            if existing_username:
                flash('Username already exists!', 'danger')
                return render_template('create.html')
            
            hashed_password = generate_password_hash(password)
            new_user = User(username=username, email=email, hashed_password=hashed_password)
            db.session.add(new_user)
            db.session.commit()

            flash(f'You have successfully added a user with username: {new_user.username}', 'success')
            return redirect(url_for('main.create'))
        else:
            flash('Invalid confirmation password!', 'danger')
            return render_template('create.html')
        
    return render_template('create.html')

@main.route('/edit/<int:user_id>', methods=['GET', 'POST'])
def edit_user(user_id):
    user = User.query.get(user_id)
    if not user:
        flash('User not found.', 'danger')
        return redirect(url_for('main.home'))

    if request.method == 'POST':
        user.username = request.form['username']
        user.email = request.form['email']
        password = request.form['password']
        confirm_password = request.form['confirm_password']
        
        if password:
            if password == confirm_password:
                user.hashed_password = generate_password_hash(password)
            else:
                flash('Passwords do not match!', 'danger')
                return render_template('edit.html', user=user)
        
        db.session.commit()
        flash(f'User {user.username} has been updated.', 'success')
        return redirect(url_for('main.home'))

    return render_template('edit.html', user=user)

@main.route('/delete_all', methods=['POST']) #html tidak support method delete secara langsung jadi make post
def delete_all_users():
    users = User.query.all()
    if not users:
        flash('Tidak ada data user', 'warning')
        return redirect(url_for('main.home'))

    for user in users:
        db.session.delete(user)
    db.session.commit()
    flash('Semua data pengguna telah dihapus.', 'success')
    return redirect(url_for('main.login'))



@main.route('/delete/<int:user_id>', methods=['POST'])
def delete_user(user_id):
    user = User.query.get(user_id)
    if user:
        db.session.delete(user)
        db.session.commit()
        flash(f'User {user.username} has been deleted.', 'success')
        if user.id == session.get('id'):
            session.clear()
            return redirect(url_for('main.login'))
    else:
        flash('User not found.', 'danger')
    return redirect(url_for('main.home'))

app/templates/create.html
<!-- templates/index.html -->
{% extends "layout.html" %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block body %}
<div class="flex items-center justify-center h-screen">
    <div class="bg-gray-900 border border-gray-200 p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 class="text-2xl font-bold mb-6 text-white text-center">Tambah User</h2>
        <form action="/create" method="POST">
            <div class="mb-4">
                <label for="username" class="block text-white font-semibold mb-2">Username</label>
                <input type="text" id="username" name="username" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="email" class="block text-white font-semibold mb-2">Email</label>
                <input type="email" id="email" name="email" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="password" class="block text-white font-semibold mb-2">Password</label>
                <input type="password" id="password" name="password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="confirm_password" class="block text-white font-semibold mb-2">Konfirmasi Password</label>
                <input type="password" id="confirm_password" name="confirm_password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <button type="submit" class="mb-2 w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-300">Tambah</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                <div class="container">
                    <li class="text-center text-white mt-4 p-4 rounded-lg mb-2 
                    {% if category == 'success' %}
                    bg-green-700
                    {% else %}
                    bg-red-600
                    {% endif %}
                    ">{{ message }}
                </li>
                </div>
                {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}

app/templates/edit.html
<!-- templates/edit.html -->
{% extends "layout.html" %}

{% block head %}
<title>Edit User</title>
{% endblock %}

{% block body %}
<div class="flex items-center justify-center h-screen">
    <div class="bg-gray-900 border border-gray-200 p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 class="text-2xl font-bold mb-6 text-white text-center">Edit User</h2>
        <form action="{{ url_for('main.edit_user', user_id=user.id) }}" method="POST">
            <div class="mb-4">
                <label for="username" class="block text-white font-semibold mb-2">Username</label>
                <input type="text" id="username" name="username" value="{{ user.username }}" placeholder="{{ user.username }}" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="email" class="block text-white font-semibold mb-2">Email</label>
                <input type="email" id="email" name="email" value="{{ user.email }}" placeholder="{{ user.email }}" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="password" class="block text-white font-semibold mb-2">Password (leave blank to keep current password)</label>
                <input type="password" id="password" name="password" placeholder="New password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            </div>
            <div class="mb-4">
                <label for="confirm_password" class="block text-white font-semibold mb-2">Confirm Password</label>
                <input type="password" id="confirm_password" name="confirm_password" placeholder="Confirm new password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            </div>
            <button type="submit" class="mb-2 w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-300">Update</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                <div class="container">
                    <li class="text-center text-white mt-4 p-4 rounded-lg mb-2 
                    {% if category == 'success' %}
                    bg-green-700
                    {% else %}
                    bg-red-600
                    {% endif %}
                    ">{{ message }}</li>
                </div>
                {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
        <p class="mt-2 text-center text-gray-200">Back to <a href="{{ url_for('main.home') }}" class="text-blue-500 underline">Dashboard</a></p>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "layout.html" %}

{% block head %}
<title>Dashboard</title>
{% endblock %}

{% block body %}

<form method="POST" action="{{ url_for('main.logout') }}" class="text-right mr-8 mt-8">
    <button type="submit" class="bg-red-600 text-white py-2 px-4 rounded-lg hover:bg-red-700 transition duration-300">
        Logout
    </button>
</form>
<div class="flex items-center justify-center h-full mt-20">
    <div class="bg-gray-800 border border-gray-200 p-8 rounded-lg shadow-lg w-full max-w-4xl mx-auto mt-10">
        <h2 class="text-2xl font-bold mb-6 text-white text-center">User List</h2>
        <table class="min-w-full mb-2 bg-white border border-gray-200 rounded-lg overflow-hidden">
            <thead class="bg-gray-700 text-white">
                <tr>
                    <th class="py-3 px-4 border-b">Username</th>
                    <th class="py-3 px-4 border-b">Email</th>
                    <th class="py-3 px-4 border-b">Role</th>
                    <th class="py-3 px-4 border-b">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users.items %}
                <tr class="bg-gray-100 even:bg-gray-200">
                    <td class="py-3 px-4 border-b">{{ user.username }}</td>
                    <td class="py-3 px-4 border-b">{{ user.email }}</td>
                    <td class="py-3 px-4 border-b">{{ user.role }}</td>
                    <td class="py-3 px-4 border-b text-center">
                        <a href="{{ url_for('main.edit_user', user_id=user.id) }}" class="text-blue-700 mx-2">edit</a>
                        <form method="POST" action="{{ url_for('main.delete_user', user_id=user.id) }}" class="inline">
                            <button type="submit" class="text-red-600 mx-2" onclick="return confirm('Apakah Anda yakin ingin menghapus data pengguna dengan username {{ user.username }}?')">delete</button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4 flex">
            {% if users.has_prev %}
                <a href="{{ url_for('main.home', page=users.prev_num) }}" class="px-4 py-2 bg-gray-700 text-white rounded-lg">Previous</a>
            {% endif %}
            <div class="flex-grow"></div>
            {% if users.has_next %}
                <a href="{{ url_for('main.home', page=users.next_num) }}" class="text-right px-4 py-2 bg-gray-700 text-white rounded-lg">Next</a>
            {% endif %}
        </div>
        <div class="mt-4 flex justify-center">
            <a href="/create" 
            class="flex items-center justify-center mx-2 px-4 py-2 bg-blue-600 text-gray-900 rounded-lg shadow-md hover:bg-blue-700 transition duration-300">
            <svg class="w-6 h-6 mr-2 text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M9 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4H7Zm8-1a1 1 0 0 1 1-1h1v-1a1 1 0 1 1 2 0v1h1a1 1 0 1 1 0 2h-1v1a1 1 0 1 1-2 0v-1h-1a1 1 0 0 1-1-1Z" clip-rule="evenodd"/>
              </svg>
                <span class="text-gray-200">Tambah User</span>
            </a>
            <form method="POST" action="{{ url_for('main.delete_all_users') }}" class="inline">
                <button type="submit" 
                class="flex items-center justify-center mx-2 px-4 py-2 bg-red-500 text-gray-900 rounded-lg shadow-md hover:bg-red-600 transition duration-300"
                onclick="return confirm('Apakah Anda yakin ingin menghapus semua data pengguna?')">
                    <svg class="w-6 h-6 mr-2 text-gray-200" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M8.586 2.586A2 2 0 0 1 10 2h4a2 2 0 0 1 2 2v2h3a1 1 0 1 1 0 2v12a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V8a1 1 0 0 1 0-2h3V4a2 2 0 0 1 .586-1.414ZM10 6h4V4h-4v2Zm1 4a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Zm4 0a1 1 0 1 0-2 0v8a1 1 0 1 0 2 0v-8Z" clip-rule="evenodd"/>
                    </svg>
                    <span class="text-gray-200">Hapus Semua</span>
                </button>
            </form>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                <div class="container">
                    <li class="text-center text-white mt-4 p-4 rounded-lg mb-2 
                    {% if category == 'success' %}
                    bg-green-700
                    {% else %}
                    bg-red-600
                    {% endif %}
                    ">{{ message }}</li>
                </div>
                {% endfor %}
            </ul>
        {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}

app/templates/layout.html
<!-- templates/layout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Flask App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="{{url_for('static', filename='dist/css/output.css')}}">
    {% block head %}
    {% endblock %}
</head>
<body class="bg-gray-900">
    {% block body %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.5.2/dist/flowbite.min.js"></script>
</body>
</html>

app/templates/login.html
<!-- templates/index.html -->
{% extends "layout.html" %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="flex items-center justify-center h-screen">
    <div class="bg-gray border border-gray-200 p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 class="text-2xl font-bold mb-6 text-white text-center">Login</h2>
        <form action="/login" method="POST">
            <div class="mb-4">
                <label for="username" class="block text-white font-semibold mb-2">Username</label>
                <input type="text" id="username" name="username" class="text-white w-full px-3 py-2 bg-gray-800 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="password" class="block text-white font-semibold mb-2">Password</label>
                <input type="password" id="password" name="password" class="text-white w-full px-3 py-2 bg-gray-800 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <button type="submit" class="mb-2 w-full bg-green-600 text-white py-2 rounded-lg hover:bg-green-700 transition duration-300">Login</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                <div class="container">
                    <li class="text-center text-white mt-4 p-4 rounded-lg mb-2 
                    {% if category == 'success' %}
                    bg-green-700
                    {% else %}
                    bg-red-600
                    {% endif %}
                    ">{{ message }}
                </li>
                </div>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
        <p class="mt-2 text-center text-gray-200">Don't have an account? <a href="{{ url_for('main.register') }}" class="text-blue-500 underline">Sign up here.</a></p>
    </div>
</div>
{% endblock %}

app/templates/register.html
<!-- templates/index.html -->
{% extends "layout.html" %}

{% block head %}
<title>Register</title>
{% endblock %}

{% block body %}
<div class="flex items-center justify-center h-screen">
    <div class="bg-gray-900 border border-gray-200 p-8 rounded-lg shadow-lg w-full max-w-md">
        <h2 class="text-2xl font-bold mb-6 text-white text-center">Register</h2>
        <form action="/register" method="POST">
            <div class="mb-4">
                <label for="username" class="block text-white font-semibold mb-2">Username</label>
                <input type="text" id="username" name="username" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="email" class="block text-white font-semibold mb-2">Email</label>
                <input type="email" id="email" name="email" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="password" class="block text-white font-semibold mb-2">Password</label>
                <input type="password" id="password" name="password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <div class="mb-4">
                <label for="confirm_password" class="block text-white font-semibold mb-2">Konfirmasi Password</label>
                <input type="password" id="confirm_password" name="confirm_password" class="text-white w-full px-3 py-2 border bg-gray-800 border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500" required>
            </div>
            <button type="submit" class="mb-2 w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-300">Register</button>
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul>
                {% for category, message in messages %}
                <div class="container">
                    <li class="text-center text-white mt-4 p-4 rounded-lg mb-2 
                    {% if category == 'success' %}
                    bg-green-700
                    {% else %}
                    bg-red-600
                    {% endif %}
                    ">{{ message }}
                </li>
                </div>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
        <p class="mt-2 text-center text-gray-200">Already have an account? <a href="{{ url_for('main.login') }}" class="text-blue-500 underline">Log in here.</a></p>
    </div>
</div>
{% endblock %}